#@host=http://arch.homework
@host=http://127.0.0.1:3000

### reister
POST {{host}}/order/create
Content-Type: application/json

{
  "id": "abcde",
  "userID": "kot",
  "price": "1000",
  "goods": [
    {
      "goodID": "a1",
      "num": "10",
      "goodPrice": "100"
    }
  ]
}
